<<<<<<< HEAD
CREATE TABLE CATEGORIES (
    IdCategorie SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NomCategorie VARCHAR(20) NOT NULL
);
CREATE TABLE UTILISATEURS (
    IdUtilisateur SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NomUtilisateur VARCHAR(20) NOT NULL,
    Prenom VARCHAR(20),
    Adresse VARCHAR(40),
    Ville VARCHAR(20),
    CodePostal INTEGER,
    Pays VARCHAR(20),
    Telephone INTEGER,
    Email VARCHAR(20),
    MotDePasse VARCHAR(20),
    DateNaissance DATE,
    DateInscription DATE
);
CREATE TABLE ACHETEURS (
    IdRefUtilisateur INTEGER NOT NULL UNIQUE PRIMARY KEY REFERENCES UTILISATEURS(IdUtilisateur) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VENDEURS (
    IdRefUtilisateur INTEGER NOT NULL UNIQUE PRIMARY KEY REFERENCES UTILISATEURS(IdUtilisateur) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE ARTICLES (
    IdArticle SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NomArticle VARCHAR(40) NOT NULL,
    PrixArticle FLOAT NOT NULL,
    QuantiteArticle INTEGER NOT NULL,
    DescriptionArticle VARCHAR(1000) NOT NULL,
    RefCategorie INTEGER NOT NULL REFERENCES CATEGORIES(IdCategorie) ON UPDATE CASCADE,
    RefVendeur INTEGER NOT NULL REFERENCES VENDEURS(IdRefUtilisateur) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE COMMANDES (
    IdCommande SERIAL NOT NULL UNIQUE PRIMARY KEY,
    DateCommande DATE NOT NULL,
    RefAcheteur INTEGER NOT NULL REFERENCES ACHETEURS(IdRefUtilisateur) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE CONTENIR (
    IdRefCommande INTEGER NOT NULL REFERENCES COMMANDES(IdCommande) ON UPDATE CASCADE ON DELETE CASCADE,
    IdRefArticle INTEGER NOT NULL REFERENCES ARTICLES(IdArticle) ON UPDATE CASCADE ON DELETE RESTRICT,
    Quantite INTEGER NOT NULL,
    PRIMARY KEY (IdRefCommande, IdRefArticle)
=======
CREATE TABLE CATEGORIES (
    IdCategorie SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NomCategorie VARCHAR(20) NOT NULL
);
CREATE TABLE UTILISATEURS (
    IdUtilisateur SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NomUtilisateur VARCHAR(20) NOT NULL,
    Prenom VARCHAR(20),
    Adresse VARCHAR(40),
    Ville VARCHAR(20),
    CodePostal INTEGER,
    Pays VARCHAR(20),
    Telephone INTEGER,
    Email VARCHAR(20),
    MotDePasse VARCHAR(20),
    DateNaissance DATE,
    DateInscription DATE
);
CREATE TABLE ACHETEURS (
    IdRefUtilisateur INTEGER NOT NULL UNIQUE PRIMARY KEY REFERENCES UTILISATEURS(IdUtilisateur) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VENDEURS (
    IdRefUtilisateur INTEGER NOT NULL UNIQUE PRIMARY KEY REFERENCES UTILISATEURS(IdUtilisateur) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE ARTICLES (
    IdArticle SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NomArticle VARCHAR(40) NOT NULL,
    PrixArticle FLOAT NOT NULL,
    QuantiteArticle INTEGER NOT NULL,
    DescriptionArticle VARCHAR(1000) NOT NULL,
    RefCategorie INTEGER NOT NULL REFERENCES CATEGORIES(IdCategorie) ON UPDATE CASCADE,
    RefVendeur INTEGER NOT NULL REFERENCES VENDEURS(IdRefUtilisateur) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE COMMANDES (
    IdCommande SERIAL NOT NULL UNIQUE PRIMARY KEY,
    DateCommande DATE NOT NULL,
    RefAcheteur INTEGER NOT NULL REFERENCES ACHETEURS(IdRefUtilisateur) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE CONTENIR (
    IdRefCommande INTEGER NOT NULL REFERENCES COMMANDES(IdCommande) ON UPDATE CASCADE ON DELETE CASCADE,
    IdRefArticle INTEGER NOT NULL REFERENCES ARTICLES(IdArticle) ON UPDATE CASCADE ON DELETE RESTRICT,
    Quantite INTEGER NOT NULL,
    PRIMARY KEY (IdRefCommande, IdRefArticle)
>>>>>>> 521457ac98f141eec458e34e9992cda7c61fff25
);